version: '3'
# services:
#   strapi:
#     build: ../backend/
#     image: acharab/backend:latest
#     ports:
#       - '1337:1337'
#   next:
#     build: ../frontend/
#     image: acharab/frontend:latest
#     ports:
#       - '3000:3000'


version: '3'
services:
    frontend:
        build: ../frontend/
        ports:
            - 3000:3000
        volumes:
            - ../frontend:/usr/src/app
        working_dir: /usr/src/app
        networks:
            - strapi-app

    backend:
        build: ../backend/
        volumes:
            - ../backend:/srv/app
            - /srv/app/node_modules
        ports:
            - '1337:1337'
        networks:
            - strapi-app
        # environment:
        #     DATABASE_CLIENT: postgres
        #     DATABASE_NAME: postgres
        #     DATABASE_HOST: host.docker.internal
        #     DATABASE_PORT: 5432
        #     DATABASE_USERNAME: postgres
        #     DATABASE_PASSWORD: WWerld123519??

    # postgres:
    #     image: postgres
    #     environment:
    #         POSTGRES_DB: postgres
    #         POSTGRES_USER: postgres
    #         POSTGRES_PASSWORD: WWerld123519??
    #     healthcheck:
    #         test: ["CMD-SHELL", "pg_isready -U postgres"]
    #         interval: 10s
    #         timeout: 5s
    #         retries: 5
    #     ports:
    #         - 5430:5430
    #     volumes:
    #         - ../data:/var/lib/postgresql/data

volumes:
    dataDB:

networks:
    strapi-app: